[project]
name = "autoware-wrapper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = ["sbsvf-api"]

[tool.uv.sources]
sbsvf-api = { git = "https://github.com/lolainta/sbsvf-api.git" }
